---
- name: Example playbook with conditional statements
  hosts: all
  tasks:
    - name: Install packages on Amazon Linux 2
      yum:
        name:
          - nginx
          - httpd
          - mysql
        state: present
      when: ansible_distribution == 'Amazon' and ansible_distribution_major_version == '2'

    - name: Install packages on Amazon Linux 3
      yum:
        name:
          - nginx
          - httpd
          - mariadb-server
        state: present
      when: ansible_distribution == 'Amazon' and ansible_distribution_major_version == '3'

